<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\MembreRepository' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Repository\\MembreRepository.php';

return $this->privates['App\Repository\MembreRepository'] = new \App\Repository\MembreRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
