<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDpxby5v\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDpxby5v/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDpxby5v.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDpxby5v\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDpxby5v\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Dpxby5v',
    'container.build_id' => '7057f024',
    'container.build_time' => 1556119796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDpxby5v');
